In [7]:
#https://www.youtube.com/watch?v=vo6gQz5lYRI&list=PLKnIA16_RmvZo7fp5kkIth6nRTeQQsjfX&index=4

In [5]:
'''
A corpus is a collection of authentic text or audio organized into datasets.
The set of unique words used in the text corpus is referred to as the vocabulary.
A document is a distinct text/entry.
Individual word in document is a word in NLP.

d1 = 'people watch youtube'
d2 = 'youtube watch youtube'
d3 = 'people write comment'
d4 = 'youtube write comment'

corpus = 'people watch youtube youtube watch youtube people write comment youtube write comment'

vocabulary = ['people','watch','youtube','write','comment'] here v = 5

document = d1, d2, d3, d4

words in d1 = ['people', 'watch', 'youtube']

'''

'\nA corpus is a collection of authentic text or audio organized into datasets.\nThe set of unique words used in the text corpus is referred to as the vocabulary.\nA document is a distinct text/entry.\nIndividual word in document is a word in NLP.\n'

One Hot Encodeing

In [ ]:
'''

d1 = 'people watch youtube'
d2 = 'youtube watch youtube'
d3 = 'people write comment'
d4 = 'youtube write comment'

d1 = [ [1,0,0,0,0],
       [0,1,0,0,0],
       [0,0,1,0,0] ]
       

d2 = [ [0,0,1,0,0],
       [0,1,0,0,0],
       [0,0,1,0,0] ]
    

d3 = [ [1,0,0,0,0],
       [0,0,0,1,0],
       [0,0,0,0,1] ]
       

d4 = [ [0,0,1,0,0],
       [0,0,0,1,0],
       [0,0,0,0,1] ]

order = (3,5)

This method is not used because of Sparcity of data, No fixed size of order matrix, Out of vocabulary, 
no capturing of semantics 

'''   

Bag of Words

In [1]:
 '''
 Especially used for text classification problem. 
  
                                          Classified As
                                           
d1 = 'people watch youtube'  ---------->      1
d2 = 'youtube watch youtube' ---------->      1
d3 = 'people write comment'  ---------->      0
d4 = 'youtube write comment' ---------->      0

vocabulary = ['people','watch','youtube','write','comment'] here v = 5

        | 'people' | 'watch' | 'youtube' | 'write' | 'comment' |

    d1       1         1          1            0         0
    
    d2       0         1          2            0         0
    
    d3       1         0          0            1         1
    
    d4       0         0          1            1         1

Bag of word assumes that if d1 = d2 = 1 & d3 = d4 = 0 then they must have high similarity 
and if (d1 = d2 = 1) ≠ (d3 = d4 = 0) meaning they must have less similarity.

Measuring the similarity between vectors we can find similarity 

'''
    
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['people watch youtube', 
                          'youtube watch youtube',
                          'people write comment',
                          'youtube write comment']})
df

text
0   people watch youtube
1  youtube watch youtube
2   people write comment
3  youtube write comment

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()

In [6]:
bow = cv.fit_transform(df['text'])
bow

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [7]:
print(cv.vocabulary_)

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}


In [9]:
print(bow[0].toarray())

[[0 1 1 0 1]]


In [10]:
print(bow[0])

  (0, 1)	1
  (0, 2)	1
  (0, 4)	1


In [19]:
print(bow[0].toarray())
print(df['text'][0])#'people watch youtube'

[[0 1 1 0 1]]
people watch youtube


In [20]:
print(bow[1].toarray())
print(df['text'][1])#'youtube watch youtube'

[[0 0 1 0 2]]
youtube watch youtube


In [21]:
print(bow[2].toarray())
print(df['text'][2])#'people write comment'

[[1 1 0 1 0]]
people write comment


In [22]:
print(bow[3].toarray())
print(df['text'][3])#'youtube write comment'

[[1 0 0 1 1]]
youtube write comment


In [24]:
print(cv.vocabulary_)
cv.transform(['youtube watch and write comment of youtube']).toarray()#transforming new sentance to BOW

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}


array([[1, 0, 1, 1, 2]])

In [26]:
'''
out of context word like 'and', 'of' are handled here

If binary = True

        | 'people' | 'watch' | 'youtube' | 'write' | 'comment' |

    d1       1         1          1            0         0
    
    d2       0         1          1            0         0
    
    d3       1         0          0            1         1
    
    d4       0         0          1            1         1

It look whether the word is present their or not.

Problem of BOW is Sparcity, Out of vocabulary, Ordering, 
                  sentences like 'This is good movie' and 'This is not good movie' have high similarity despite their
                  meaning is different
'''

"\nout of context word like 'and', 'of' are handled here\n\nIf binary = True\n\n        | 'people' | 'watch' | 'youtube' | 'write' | 'comment' |\n\n    d1       1         1          1            0         0\n    \n    d2       0         1          1            0         0\n    \n    d3       1         0          0            1         1\n    \n    d4       0         0          1            1         1\n\nIt look whether the word is present their or not.\n\nProblem of BOW is Sparcity, Out of vocabulary, Ordering, \n                  sentences like 'This is good movie' and 'This is not good movie' have high similarity despite their\n                  meaning is different\n"

N-Grams

In [28]:
'''
N-Grams solves word ordering problem. 

Creating bi gram OR 2-gram

d1 = 'people watch youtube'
d2 = 'youtube watch youtube'
d3 = 'people write comment'
d4 = 'youtube write comment'


    | people watch | watch youtube | youtube watch | people write | write comment | youtube write |
    
d1         1             1               0                 0             0                  0

d2         0             1               1                 0             0                  0

d3         0             1               0                 1             1                  0 

d4         0             0               0                 0             1                  1


Creating tri gram OR 3-gram


        | people watch youtube | youtube watch youtube | people write comment | youtube write comment |

d1                   1                     0                      0                        0

d2                   0                     1                      0                        0

d3                   0                     0                      1                        0

d4                   0                     0                      0                        1
 


Creating quad gram OR 4-gram error will occur here but in real textual data it will be possible because of longer length

If n = 1, uni-gram it becomes Bag Of Words (above method)
'''

"\nN-Grams solves word ordering problem. \n\nCreating bi gram OR 2-gram\n\nd1 = 'people watch youtube'\nd2 = 'youtube watch youtube'\nd3 = 'people write comment'\nd4 = 'youtube write comment'\n\n\n    | people watch | watch youtube | youtube watch | people write | write comment | youtube write |\n    \nd1         1             1               0                 0             0                  0\n\nd2         0             1               1                 0             0                  0\n\nd3         0             1               0                 1             1                  0 \n\nd4         0             0               0                 0             1                  1\n\n\nCreating tri gram OR 3-gram\n\n\n        | people watch youtube | youtube watch youtube | people write comment | youtube write comment |\n\nd1                   1                     0                      0                        0\n\nd2                   0                     1                      0  

In [36]:
#from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(ngram_range=(2,2))#ngram_range=(min_n,max_n) bi-gram

In [37]:
bow = cv.fit_transform(df['text'])
bow

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [38]:
print(cv.vocabulary_)#bi-gram case

{'people watch': 0, 'watch youtube': 2, 'youtube watch': 4, 'people write': 1, 'write comment': 3, 'youtube write': 5}


In [35]:
print(bow[0].toarray())

[[1 0 1 0 0 0]]


In [39]:
cv=CountVectorizer(ngram_range=(1,2))#ngram_range=(min_n,max_n) uni-gram + bi-gram

In [40]:
bow = cv.fit_transform(df['text'])
bow

<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [41]:
print(cv.vocabulary_)

{'people': 1, 'watch': 4, 'youtube': 8, 'people watch': 2, 'watch youtube': 5, 'youtube watch': 9, 'write': 6, 'comment': 0, 'people write': 3, 'write comment': 7, 'youtube write': 10}


In [42]:
'''
 b1 = 'this movie is very good'
 b2 = 'this movie is not very good'
 
 Example of bigram being superior to BOW 
 
 BOW
 
        | this | movie | is | very | good | not |
 
b1         1       1     1     1      1      0
 
b2         1       1     1     1      1      1
 
 
cosinesimilarity =  (1*1 + 1*1 + 1*1 + 1*1 + 1*1 + 0*1)/(sqrt(1^2+1^2+1^2+1^2+1^2)*sqrt(1^2+1^2+1^2+1^2+1^2+1^2)) 
                 = 5/sqrt(30) ~ 24°
 
==================================================================================================================== 
 
        | this movie | movie is | is very | very good | is not | not very |
        
b1            1           1          1         1          0         0

b2            1           1          0         1          1         1
 
cosine similarity = (1*1 + 1*1 + 1*0 + 1*1 + 0*1 + 0*1)/(sqrt(1^2+1^2+1^2+1^2)*sqrt(1^2+1^2+1^2+1^2+1^2)) = 3/sqrt(20) = 0.67

thitha = acos(0.67) ~ 48°

Less angle = More similarity

It captures semantic meaning
But number of tokens for large data set increases as value of N increases. Also, has no solution for out of 
vocabulary terms.
'''

"\n b1 = 'this movie is very good'\n b2 = 'this movie is not very good'\n \n Example of bigram being superior to BOW \n \n BOW\n \n        | this | movie | is | very | good | not |\n \nb1         1       1     1     1      1      0\n \nb2         1       1     1     1      1      1\n \n \ncosinesimilarity =  (1*1 + 1*1 + 1*1 + 1*1 + 1*1 + 0*1)/(sqrt(1^2+1^2+1^2+1^2+1^2)*sqrt(1^2+1^2+1^2+1^2+1^2+1^2)) \n                 = 5/sqrt(30) ~ 24°\n \n==================================================================================================================== \n \n        | this movie | movie is | is very | very good | is not | not very |\n        \nb1            1           1          1         1          0         0\n\nb2            1           1          0         1          1         1\n \ncosine similarity = (1*1 + 1*1 + 1*0 + 1*1 + 0*1 + 0*1)/(sqrt(1^2+1^2+1^2+1^2)*sqrt(1^2+1^2+1^2+1^2+1^2)) = 3/sqrt(20) = 0.67\n\nthitha = acos(0.67) ~ 48°\n\nLess angle = More similarity\n\nIt captu

TF-IDF (Term Frequency - Inverse Document Frequency)

In [43]:
'''
The problem with BOW, N-Gram is that it gives equal importance to every words  

d1 = 'people watch youtube'
d2 = 'youtube watch youtube'
d3 = 'people write comment'
d4 = 'youtube write comment'

vocabulary = ['people','watch','youtube','write','comment'] here v = 5

        | 'people' | 'watch' | 'youtube' | 'write' | 'comment' |

    d1       1         1          1            0         0
    
    d2       0         1          2            0         0
    
    d3       1         0          0            1         1
    
    d4       0         0          1            1         1
    
Here, BOW/1-Gram gave equal importance to 'people' and 'watch' but TF-IDF gives more importance to a word if its
repetation in other document is low


d1 = 'people watch youtube'
d2 = 'youtube watch youtube'
d3 = 'people write comment'
d4 = 'youtube write comment'
    
Here some words will have higher importance as and other will have less importance   
    
To calculate importance we will find TF = Term Frequency              &
                                    IDF = Inverse Document Frequency 
    
Word will have higher weightage if its occurance in document is more and less in other document.

TF (t, d) = Number_of_occurance_of_term_t_in_document_d/Total_number_of_terms_in_document_d    
    
IDF (t) = log_e ( Total_number_of_documents_in_the_corpus / Number_of_documents_with_term_t_in_them  )

vocabulary = ['people','watch','play','youtube','write','comment'] here v = 6


IF(people,d1)1/3 = d1_has_1_people / d1_has_3_words

               IF_d1            IF_d2           IF_d3           IF_d4      

people    IF(people,d1)1/3      0               1/3             0
watch          1/3              1/3             0               0
youtube        1/3              2/3             0               1/3
write          0                0               1/3             1/3
comment        0                0               1/3             1/3


d1 = 'people watch youtube'
d2 = 'youtube watch youtube'
d3 = 'people write comment'
d4 = 'youtube write comment'

IDF_d1(youtube) = log( 4 / 3 ) = log( their_are_4_documents_in_corpus / their_are_3_document_with_'youtube' )

               IDF             

people         log(4/2) ~ 0.301
watch          log(4/2) ~ 0.301
youtube        log(4/3) ~ 0.125
write          log(4/2) ~ 0.301
comment        log(4/2) ~ 0.301

IDF (t) = log_e ( Total_number_of_documents_in_the_corpus / Number_of_documents_with_term_t_in_them  )

IDF measures rarity of a word here 
                                        Total_number_of_documents_in_the_corpus is always fixed
                                        
                                        Number_of_documents_with_term_t_in_them gives rarity 
                                                  |  
                                                   -> if a term occurs is every document then its not rare
                                                   -> if a term occurs is few document then its rare
                                                   

IF Total_number_of_documents_in_the_corpus =  Number_of_documents_with_term_t_in_them then log() = 1

IF Total_number_of_documents_in_the_corpus >>  Number_of_documents_with_term_t_in_them then log() >> 1

So, TF-IDF = TF * IDF

TF-TDF for above text is

               IF_IDF         IF_IDF          IF_IDF         IF_IDF      

people         1/3*0.301        0               1/3*0.301       0
watch          1/3*0.301        1/3*0.301       0               0
youtube        1/3*0.125        2/3*0.125       0               1/3*0.125
write          0                0               1/3*0.301       1/3*0.301
comment        0                0               1/3*0.301       1/3*0.301

=====================================================================================================================

               IF_IDF         IF_IDF          IF_IDF         IF_IDF      

people         0.1              0               0.1             0
watch          0.1              0.1             0               0
youtube        0.04             0.08            0               0.04
write          0                0               0.1             0.1
comment        0                0               0.1             0.1

=====================================================================================================================

'''

"\nThe problem with BOW, N-Gram is that it gives equal importance to every words  \n\nd1 = 'people watch youtube'\nd2 = 'youtube watch youtube'\nd3 = 'people write comment'\nd4 = 'youtube write comment'\n\nvocabulary = ['people','watch','youtube','write','comment'] here v = 5\n\n        | 'people' | 'watch' | 'youtube' | 'write' | 'comment' |\n\n    d1       1         1          1            0         0\n    \n    d2       0         1          2            0         0\n    \n    d3       1         0          0            1         1\n    \n    d4       0         0          1            1         1\n    \nHere, BOW/1-Gram gave equal importance to 'people' and 'watch' but TF-IDF gives more importance to a word if its\nrepetation in other document is low\n\n\nd1 = 'people watch youtube'\nd2 = 'youtube watch youtube'\nd3 = 'people write comment'\nd4 = 'youtube write comment'\n    \nHere some words will have higher importance as and other will have less importance   \n    \nTo calculate imp

In [44]:
df

text
0   people watch youtube
1  youtube watch youtube
2   people write comment
3  youtube write comment

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])

In [53]:
print(tfidf.vocabulary_)

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}


In [59]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.51082562 1.22314355]
['comment' 'people' 'watch' 'write' 'youtube']


In [60]:
'''
Notice that our calculated value is different from above becauyse above algorithm uses

   IDF(t) = log ( n / df(t)) + 1
    
   1 is added because for word that repeats in every term will not be ignored
   
   Ideal textbook defines formula as 
   
   DF(t) = log ( n / (df(t)+1) )
   
   
Another Qn can be why take log  in IDF?

If IDF = N/n

Suppose 10,000 movie review we have a common word 'the' then IDF = 1 = 10000/10000

                            we have rare word 'encyclopedia' then IDF = 10000 = 10000/1
                            
which will be a problem because 10,000 is very large factor as it will dominate TF * IDF product

if log is used 'the' IDF = 0
if log is used 'encyclopedia' IDF = 4

TF-IDF is used in information retrieval system.

If vocabulary = v is big then then we might bet lot of sparse array
Out of vocabulary problem
Dimensionality increases as v increases and brings problem of overfitting
Cant capture semantic relation
          This is beautiful
          This is gorgeous
 
'''

"\nNotice that our calculated value is different from above becauyse above algorithm uses\n\n   IDF(t) = log ( n / df(t)) + 1\n    \n   1 is added because for word that repeats in every term will not be ignored\n   \n   Ideal textbook defines formula as \n   \n   DF(t) = log ( n / (df(t)+1) )\n   \n   \nAnother Qn can be why take log  in IDF?\n\nIf IDF = N/n\n\nSuppose 10,000 movie review we have a common word 'the' then IDF = 1 = 10000/10000\n\n                            we have rare word 'encyclopedia' then IDF = 10000 = 10000/1\n                            \nwhich will be a problem because 10,000 is very large factor as it will dominate TF * IDF product\n\nif log is used 'the' IDF = 0\nif log is used 'encyclopedia' IDF = 4\n\nTF-IDF is used in information retrieval system.\n\nIf vocabulary = v is big then then we might bet lot of sparse array\nOut of vocabulary problem\nDimensionality increases as v increases and brings problem of overfitting\nCant capture semantic relation\n      